### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by amir650**

### CODE REVIEW

**Comment by amir650** [comment]
Adding License.

**Comment by Beesboertjie** [comment]
please unsubscribe me

**Comment by amir650** [comment]
Hi - I'm not sure I understand your comment.  Is unsubscribing not something you can do yourself?

**Comment by Beesboertjie** [comment]
Hi amir650. Thank you for your response. I enjoyed everything, but I found a new interest.  Yes, it looks like I can unsubscribe myself, I found a tab (or something) above which I checked "Ignoring (never be notified)". Have a nice day. Have a nice new year.

**Pull request merged**
